### ISSUE TITLE
Build failure under Linux 3.14 with free-threading

### ISSUE THREAD

**Issue by clin1234** [binref/refinery#53]
Got the following log:
```
...
  Collecting msgpack>=1.0.0
    Using cached msgpack-1.0.8.tar.gz (167 kB)
    Installing build dependencies: started
    Running command pip subprocess to install build dependencies
    Using pip 24.2 from /workspaces/venv/lib/python3.14t/site-packages/pip (python 3.14)
    Collecting Cython~=3.0.8
      Obtaining dependency information for Cython~=3.0.8 from https://files.pythonhosted.org/packages/43/39/bdbec9142bc46605b54d674bf158a78b191c2b75be527c6dcf3e6dfe90b8/Cython-3.0.11-py2.py3-none-any.whl.metadata
      Using cached Cython-3.0.11-py2.py3-none-any.whl.metadata (3.2 kB)
    Collecting setuptools>=35.0.2
      Obtaining dependency information for setuptools>=35.0.2 from https://files.pythonhosted.org/packages/6e/ec/06715d912351edc453e37f93f3fc80dcffd5ca0e70386c87529aca296f05/setuptools-72.2.0-py3-none-any.whl.metadata
      Using cached setuptools-72.2.0-py3-none-any.whl.metadata (6.6 kB)
    Using cached Cython-3.0.11-py2.py3-none-any.whl (1.2 MB)
    Using cached setuptools-72.2.0-py3-none-any.whl (2.3 MB)
    Installing collected packages: setuptools, Cython
      Creating /tmp/pip-build-env-4jdpxvmr/overlay/bin
      changing mode of /tmp/pip-build-env-4jdpxvmr/overlay/bin/cygdb to 757
      changing mode of /tmp/pip-build-env-4jdpxvmr/overlay/bin/cython to 757
      changing mode of /tmp/pip-build-env-4jdpxvmr/overlay/bin/cythonize to 757
    Successfully installed Cython-3.0.11 setuptools-72.2.0
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Running command Getting requirements to build wheel
    running egg_info
    writing msgpack.egg-info/PKG-INFO
    writing dependency_links to msgpack.egg-info/dependency_links.txt
    writing top-level names to msgpack.egg-info/top_level.txt
    reading manifest file 'msgpack.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.c' under directory 'msgpack'
    adding license file 'COPYING'
    writing manifest file 'msgpack.egg-info/SOURCES.txt'
    Getting requirements to build wheel: finished with status 'done'
    Preparing metadata (pyproject.toml): started
    Running command Preparing metadata (pyproject.toml)
    running dist_info
    creating /tmp/pip-modern-metadata-w23ik30t/msgpack.egg-info
    writing /tmp/pip-modern-metadata-w23ik30t/msgpack.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-modern-metadata-w23ik30t/msgpack.egg-info/dependency_links.txt
    writing top-level names to /tmp/pip-modern-metadata-w23ik30t/msgpack.egg-info/top_level.txt
    writing manifest file '/tmp/pip-modern-metadata-w23ik30t/msgpack.egg-info/SOURCES.txt'
    reading manifest file '/tmp/pip-modern-metadata-w23ik30t/msgpack.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.c' under directory 'msgpack'
    adding license file 'COPYING'
    writing manifest file '/tmp/pip-modern-metadata-w23ik30t/msgpack.egg-info/SOURCES.txt'
    creating '/tmp/pip-modern-metadata-w23ik30t/msgpack-1.0.8.dist-info'
    Preparing metadata (pyproject.toml): finished with status 'done'
  Collecting pefile
    Obtaining dependency information for pefile from https://files.pythonhosted.org/packages/55/26/d0ad8b448476d0a1e8d3ea5622dc77b916db84c6aa3cb1e1c0965af948fc/pefile-2023.2.7-py3-none-any.whl.metadata
    Using cached pefile-2023.2.7-py3-none-any.whl.metadata (1.4 kB)
  Collecting pycryptodomex
    Using cached pycryptodomex-3.20.0.tar.gz (4.8 MB)
    Installing build dependencies: started
    Running command pip subprocess to install build dependencies
    Using pip 24.2 from /workspaces/venv/lib/python3.14t/site-packages/pip (python 3.14)
    Collecting setuptools
      Obtaining dependency information for setuptools from https://files.pythonhosted.org/packages/6e/ec/06715d912351edc453e37f93f3fc80dcffd5ca0e70386c87529aca296f05/setuptools-72.2.0-py3-none-any.whl.metadata
      Using cached setuptools-72.2.0-py3-none-any.whl.metadata (6.6 kB)
    Using cached setuptools-72.2.0-py3-none-any.whl (2.3 MB)
    Installing collected packages: setuptools
    Successfully installed setuptools-72.2.0
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Running command Getting requirements to build wheel
...
  Building wheels for collected packages: msgpack, pycryptodomex
    Building wheel for msgpack (pyproject.toml): started
    Running command Building wheel for msgpack (pyproject.toml)
    running bdist_wheel
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-cpython-314t
    creating build/lib.linux-x86_64-cpython-314t/msgpack
    copying msgpack/fallback.py -> build/lib.linux-x86_64-cpython-314t/msgpack
    copying msgpack/exceptions.py -> build/lib.linux-x86_64-cpython-314t/msgpack
    copying msgpack/__init__.py -> build/lib.linux-x86_64-cpython-314t/msgpack
    copying msgpack/ext.py -> build/lib.linux-x86_64-cpython-314t/msgpack
    running build_ext
    building 'msgpack._cmsgpack' extension
    creating build/temp.linux-x86_64-cpython-314t
    creating build/temp.linux-x86_64-cpython-314t/msgpack
    x86_64-linux-gnu-g++ -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O2 -Wall -g -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I. -I/workspaces/venv/include -I/usr/include/python3.14t -c msgpack/_cmsgpack.cpp -o build/temp.linux-x86_64-cpython-314t/msgpack/_cmsgpack.o
    msgpack/_cmsgpack.cpp:1366:72: warning: ‘Py_UNICODE’ is deprecated [-Wdeprecated-declarations]
     1366 | static CYTHON_INLINE size_t __Pyx_Py_UNICODE_strlen(const Py_UNICODE *u)
          |                                                                        ^
    In file included from /usr/include/python3.14t/unicodeobject.h:1014,
                     from /usr/include/python3.14t/Python.h:76,
                     from msgpack/_cmsgpack.cpp:16:
    /usr/include/python3.14t/cpython/unicodeobject.h:10:37: note: declared here
       10 | Py_DEPRECATED(3.13) typedef wchar_t Py_UNICODE;
          |                                     ^~~~~~~~~~
    msgpack/_cmsgpack.cpp: In function ‘size_t __Pyx_Py_UNICODE_strlen(const Py_UNICODE*)’:
    msgpack/_cmsgpack.cpp:1368:23: warning: ‘Py_UNICODE’ is deprecated [-Wdeprecated-declarations]
     1368 |     const Py_UNICODE *u_end = u;
          |                       ^~~~~
    In file included from /usr/include/python3.14t/unicodeobject.h:1014,
                     from /usr/include/python3.14t/Python.h:76,
                     from msgpack/_cmsgpack.cpp:16:
    /usr/include/python3.14t/cpython/unicodeobject.h:10:37: note: declared here
       10 | Py_DEPRECATED(3.13) typedef wchar_t Py_UNICODE;
          |                                     ^~~~~~~~~~
    msgpack/_cmsgpack.cpp: In function ‘int __Pyx_CheckKeywordStrings(PyObject*, const char*, int)’:
    msgpack/_cmsgpack.cpp:19109:9: error: ‘CYTHON_METH_FASTCALL’ was not declared in this scope; did you mean ‘METH_FASTCALL’?
    19109 |     if (CYTHON_METH_FASTCALL && likely(PyTuple_Check(kw))) {
          |         ^~~~~~~~~~~~~~~~~~~~
          |         METH_FASTCALL
    msgpack/_cmsgpack.cpp: In function ‘int __Pyx_ParseOptionalKeywords(PyObject*, PyObject* const*, PyObject***, PyObject*, PyObject**, Py_ssize_t, const char*)’:
    msgpack/_cmsgpack.cpp:19198:25: error: ‘CYTHON_METH_FASTCALL’ was not declared in this scope; did you mean ‘METH_FASTCALL’?
    19198 |     int kwds_is_tuple = CYTHON_METH_FASTCALL && likely(PyTuple_Check(kwds));
          |                         ^~~~~~~~~~~~~~~~~~~~
          |                         METH_FASTCALL
    error: command '/usr/bin/x86_64-linux-gnu-g++' failed with exit code 1
    error: subprocess-exited-with-error

    × Building wheel for msgpack (pyproject.toml) did not run successfully.
    │ exit code: 1
    ╰─> See above for output.

    note: This error originates from a subprocess, and is likely not a problem with pip.
    full command: /workspaces/venv/bin/python3.14t /workspaces/venv/lib/python3.14t/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py build_wheel /tmp/tmpwebmrrqb
    cwd: /tmp/pip-install-d715fpyo/msgpack_a1078e0309324d2fb789c24e9e98d290
    Building wheel for msgpack (pyproject.toml): finished with status 'error'
    ERROR: Failed building wheel for msgpack
    Building wheel for pycryptodomex (pyproject.toml): started
    Running command Building wheel for pycryptodomex (pyproject.toml)
    /tmp/pip-build-env-ccc_xdwh/overlay/lib/python3.14t/site-packages/setuptools/dist.py:447: SetuptoolsDeprecationWarning: Invalid dash-separated options
    !!
...
    running install_egg_info
    running egg_info
    writing lib/pycryptodomex.egg-info/PKG-INFO
    writing dependency_links to lib/pycryptodomex.egg-info/dependency_links.txt
    writing top-level names to lib/pycryptodomex.egg-info/top_level.txt
    reading manifest file 'lib/pycryptodomex.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    no previously-included directories found matching 'Doc/_build'
    warning: no previously-included files matching '*.pyc' found under directory 'src'
    no previously-included directories found matching 'src/test/build'
    adding license file 'LICENSE.rst'
    adding license file 'AUTHORS.rst'
    writing manifest file 'lib/pycryptodomex.egg-info/SOURCES.txt'
    Copying lib/pycryptodomex.egg-info to build/bdist.linux-x86_64/wheel/./pycryptodomex-3.20.0-py3.14.egg-info
    running install_scripts
    Traceback (most recent call last):
      File "/workspaces/venv/lib/python3.14t/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
        main()
        ~~~~^^
      File "/workspaces/venv/lib/python3.14t/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
                                 ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
      File "/workspaces/venv/lib/python3.14t/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
        return _build_backend().build_wheel(wheel_directory, config_settings,
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                            metadata_directory)
                                            ^^^^^^^^^^^^^^^^^^^
      File "/tmp/pip-build-env-ccc_xdwh/overlay/lib/python3.14t/site-packages/setuptools/build_meta.py", line 415, in build_wheel
        return self._build_with_temp_dir(
               ~~~~~~~~~~~~~~~~~~~~~~~~~^
            ['bdist_wheel'],
            ^^^^^^^^^^^^^^^^
        ...<3 lines>...
            self._arbitrary_args(config_settings),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        )
        ^
      File "/tmp/pip-build-env-ccc_xdwh/overlay/lib/python3.14t/site-packages/setuptools/build_meta.py", line 397, in _build_with_temp_dir
        self.run_setup()
        ~~~~~~~~~~~~~~^^
      File "/tmp/pip-build-env-ccc_xdwh/overlay/lib/python3.14t/site-packages/setuptools/build_meta.py", line 313, in run_setup
        exec(code, locals())
        ~~~~^^^^^^^^^^^^^^^^
      File "<string>", line 500, in <module>
      File "/tmp/pip-build-env-ccc_xdwh/overlay/lib/python3.14t/site-packages/setuptools/__init__.py", line 108, in setup
        return distutils.core.setup(**attrs)
               ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
      File "/tmp/pip-build-env-ccc_xdwh/overlay/lib/python3.14t/site-packages/setuptools/_distutils/core.py", line 184, in setup
        return run_commands(dist)
      File "/tmp/pip-build-env-ccc_xdwh/overlay/lib/python3.14t/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
        dist.run_commands()
        ~~~~~~~~~~~~~~~~~^^
      File "/tmp/pip-build-env-ccc_xdwh/overlay/lib/python3.14t/site-packages/setuptools/_distutils/dist.py", line 964, in run_commands
        self.run_command(cmd)
        ~~~~~~~~~~~~~~~~^^^^^
      File "/tmp/pip-build-env-ccc_xdwh/overlay/lib/python3.14t/site-packages/setuptools/dist.py", line 945, in run_command
        super().run_command(command)
        ~~~~~~~~~~~~~~~~~~~^^^^^^^^^
      File "/tmp/pip-build-env-ccc_xdwh/overlay/lib/python3.14t/site-packages/setuptools/_distutils/dist.py", line 983, in run_command
        cmd_obj.run()
        ~~~~~~~~~~~^^
      File "/tmp/pip-build-env-ccc_xdwh/overlay/lib/python3.14t/site-packages/setuptools/command/bdist_wheel.py", line 410, in run
        impl_tag, abi_tag, plat_tag = self.get_tag()
                                      ~~~~~~~~~~~~^^
      File "/tmp/pip-build-env-ccc_xdwh/overlay/lib/python3.14t/site-packages/setuptools/command/bdist_wheel.py", line 360, in get_tag
        tag in supported_tags
    AssertionError: would build wheel with unsupported tag ('cp35', 'abi3', 'linux_x86_64')
    error: subprocess-exited-with-error

    × Building wheel for pycryptodomex (pyproject.toml) did not run successfully.
    │ exit code: 1
    ╰─> See above for output.

    note: This error originates from a subprocess, and is likely not a problem with pip.
    full command: /workspaces/venv/bin/python3.14t /workspaces/venv/lib/python3.14t/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py build_wheel /tmp/tmpfgt_3ucy
    cwd: /tmp/pip-install-d715fpyo/pycryptodomex_3e572a56c4974502984104a416dd7238
    Building wheel for pycryptodomex (pyproject.toml): finished with status 'error'
    ERROR: Failed building wheel for pycryptodomex
  Failed to build msgpack pycryptodomex
  ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (msgpack, pycryptodomex)
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /workspaces/venv/bin/python3.14t /workspaces/venv/lib/python3.14t/site-packages/pip/__pip-runner__.py install --ignore-installed --no-user --prefix /tmp/pip-build-env-59dw6c9z/overlay --no-warn-script-location --disable-pip-version-check -v --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- colorama defusedxml macholib 'msgpack>=1.0.0' pefile pycryptodomex pyelftools setuptools toml wheel
  cwd: [inherit]
  Installing build dependencies: finished with status 'error'
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

```
Two dependencies should be bumped: pycryptodex (https://github.com/Legrandin/pycryptodome/issues/813) and cython

**Comment by huettenhain** [comment]
What do you mean by "bumped"?

**Comment by huettenhain** [comment]
The [pycryptodomex package does not have a version requirement via refinery](https://github.com/binref/refinery/blob/master/pyproject.toml#L8), and I do not understand the reference to cython. Since there hasn't been any response to my above question in 2 weeks, I will close this out as stale & lacking context.
