### ISSUE TITLE
IFPS: EOFError on possible corrupted file

### ISSUE THREAD

**Issue by gdesmar** [binref/refinery#70]
### Description
When reading this specific IFPS file with the IFPS unit, the following error happens:
> failure in ifps: exception of type EOFError

Full output with -vv:
```python
failure in ifps: exception of type EOFError
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
00.742 kB; 50.86% entropy; data
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
0000: 49 46 50 53 15 00 00 00 0F 00 00 00 07 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 0D 00 00 00 00 09 00 00 00 00 08 00 00 00 00 07 00 00 00 00 0A 00 00 00 00 05 00 00  IFPS....................................................
0038: 00 00 06 00 00 00 00 04 00 00 00 00 03 00 00 00 00 02 00 00 00 00 12 00 00 00 00 01 00 00 00 00 01 00 00 00 00 8F 05 00 00 00 43 6C 61 73 73 0B 00 00 00 54 57 49 5A 41  ..........................................Class....TWIZA
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File ".../refinery/units/__init__.py", line 1489, in normalized_action
    yield from self.act(data)
  File ".../refinery/units/__init__.py", line 1836, in act
    it = self.process(data)
         ^^^^^^^^^^^^^^^^^^
  File ".../refinery/units/__init__.py", line 864, in wrapped
    result = operation(self, data)
             ^^^^^^^^^^^^^^^^^^^^^
  File ".../refinery/units/formats/ifps.py", line 914, in process
    return str(IFPSFile(data)).encode(self.codec)
               ^^^^^^^^^^^^^^
  File ".../refinery/lib/structures.py", line 711, in wrapped__init__
    original__init__(self, reader, *args, **kwargs)
  File ".../refinery/units/formats/ifps.py", line 595, in __init__
    self._load_types()
  File ".../refinery/units/formats/ifps.py", line 640, in _load_types
    t.attributes = list(self._read_attributes())
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../refinery/units/formats/ifps.py", line 683, in _read_attributes
    fields = tuple(self._read_value() for _ in range(reader.u32()))
                                                     ^^^^^^^^^^^^
  File ".../refinery/lib/structures.py", line 600, in u32
    def u32(self, peek: bool = False) -> int: return self.read_integer(32, peek)
                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../refinery/lib/structures.py", line 484, in read_integer
    raise EOFError
EOFError
```

### To Reproduce
The original [InnoSetup file](https://www.virustotal.com/gui/file/3361ab3a761324a1828828f470355c82e5fdce461d3199aa92c199c1a3fc27b6) gives out an IFPS file named [CompiledCode.bin](https://github.com/user-attachments/files/17874426/CompiledCode.bin.zip)  (attached, with password `binref`). This is the file causing the issue.

### Environment
- Operating System: Debian bullseye
- Python Version: Python 3.11.7
- Refinery Version: Tried with both 0.7.2 and 0.7.8

### Additional Context
I do believe the input file is small and could be corrupted. I tried using both innoextract (linux) and innounp (using wine) on the original InnoSetup file, and even if they both give the same CompiledCode.bin, it doesn't mean they are both right. I wanted to raise awareness of this crash, but if the input file is corrupted/missing content, crashing out may be the right behaviour and we can close this issue.

**Comment by huettenhain** [comment]
There was indeed something wrong. I am not 100% I got it right, but I am like 95% sure. I don't have a great test corpus for IFPS files, so I will have to rely on your bug reports - if my fix breaks files that previously worked fine, please let me know and I will revise this.

**Comment by huettenhain** [comment]
Currently [releasing](https://github.com/binref/refinery/actions/runs/11985350146) 0.7.9; this bugfix is included in that release.

**Comment by huettenhain** [comment]
For the record, this is the current output:
```
WIZARDFORM: Class;

external symbol SHOULDPROCESSENTRY;
external symbol REGQUERYSTRINGVALUE;
external symbol EXTRACTFILEDIR;
external symbol COMPARETEXT;
external symbol EXPANDCONSTANT;

begin symbol F0
  0x000  Ret         
end symbol

begin function NEEDRESTART() -> U08
  0x000  PushType    String
  0x005  PushType    U08
  0x00A  PushType    U08
  0x00F  PushType    String
  0x014  Assign      LocalVar4, 'shellextension'
  0x031  PushType    String
  0x036  Assign      LocalVar5, ''
  0x045  PushVar     LocalVar3
  0x04B  Call        SHOULDPROCESSENTRY
  0x050  Pop         
  0x051  Pop         
  0x052  Pop         
  0x053  Compare     LocalVar2, LocalVar3 == 1
  0x065  Pop         
  0x066  PushType    U08
  0x06B  PushType    Pointer
  0x070  SetPtr      LocalVar4, LocalVar1
  0x07B  PushType    String
  0x080  Assign      LocalVar5, ''
  0x08F  PushType    String
  0x094  Assign      LocalVar6, 'CLSID\\{B22A40F0-BD69-11D3-8D28-006097C82E57}\\InProcServer32'
  0x0DE  PushType    S32
  0x0E3  Assign      LocalVar7, -2147483648
  0x0F2  PushVar     LocalVar3
  0x0F8  Call        REGQUERYSTRINGVALUE
  0x0FD  Pop         
  0x0FE  Pop         
  0x0FF  Pop         
  0x100  Pop         
  0x101  Pop         
  0x102  Calculate   LocalVar2 &= LocalVar3
  0x10E  Pop         
  0x10F  SetFlag     LocalVar2, 1
  0x116  Pop         
  0x117  JumpFlag    0x1C9
  0x11C  PushType    String
  0x121  Assign      LocalVar2, LocalVar1
  0x12C  PushVar     LocalVar1
  0x132  Call        EXTRACTFILEDIR
  0x137  Pop         
  0x138  Pop         
  0x139  Compare     Argument1, LocalVar1 != ''
  0x14E  PushType    U08
  0x153  PushType    S32
  0x158  PushType    String
  0x15D  PushType    String
  0x162  Assign      LocalVar5, '{app}'
  0x176  PushVar     LocalVar4
  0x17C  Call        EXPANDCONSTANT
  0x181  Pop         
  0x182  Pop         
  0x183  PushType    String
  0x188  Assign      LocalVar5, LocalVar1
  0x193  PushVar     LocalVar3
  0x199  Call        COMPARETEXT
  0x19E  Pop         
  0x19F  Pop         
  0x1A0  Pop         
  0x1A1  Compare     LocalVar2, LocalVar3 != 0
  0x1B6  Pop         
  0x1B7  Calculate   Argument1 &= LocalVar2
  0x1C3  Pop         
  0x1C4  Jump        0x1D5
  0x1C9  Assign      Argument1, 0
  0x1D5  Ret         
end function
```
