### ISSUE TITLE
Explorer Raises AttributeError After Version Upgrade

### ISSUE THREAD

**Issue by utkonos** [binref/refinery#71]
### Description
After each version upgrade via `pip install -U binary-refinery` the pickled unit cache becomes corrupted. When a new version has been installed from pypi, the following is shown after trying `binref foo`:

```none
% binref foo 
_________ __       __________     ______
\_____   \__| ____/   ______/____/ ____/
 ||  | __/  |/    \  /__|  / __ \   __/ 
 ||  |   \  |   |  \_  _| \  ___/|  |   
 ||____  /__|___|__/  / |  \____]|__|   
 ======\/=========\  /==|__|============
   binary refinery \/ full text search  

Traceback (most recent call last):
  File "/Users/username/Applications/BinaryRefinery/venv/bin/binref", line 8, in <module>
    sys.exit(explorer())
             ~~~~~~~~^^
  File "/Users/username/Applications/BinaryRefinery/venv/lib/python3.13/site-packages/refinery/explore.py", line 157, in explorer
    unit = getattr(refinery, name)
  File "/Users/username/Applications/BinaryRefinery/venv/lib/python3.13/site-packages/refinery/__init__.py", line 205, in __getattr__
    raise AttributeError(name)
AttributeError: httprequest
```

### To Reproduce
When a new version is available and detected via `pip list -o`, just run: `pip install -U binary-refinery`. Then run `binref foo`.

### Environment
- Operating System: macOS
- Python Version: 3.13.0
- Refinery Version: 0.7.10

### Additional Context
I first noted this in the following discussion:
https://github.com/binref/refinery/discussions/65

And the following workaround works 100%, so this bug is just annoying/cosmetic. No real need to fix it, but it does happen every time after upgrade:

```zsh
rm ~/Applications/BinaryRefinery/venv/lib/*/site-packages/refinery/__init__.pkl
```

Also of note is the very first time after deleting the pickle, the following error is shown. Any subsequent run of the exact same command, and this error is not printed a second or any other time. That first time the expected output is also printed immediately after the error.

```none
ERROR:root:could not load refinery.units.formats.httprequest because cgi is missing.
```

**Comment by huettenhain** [comment]
Wow, Github is really eager to close issues automatically even though the commit message only says "attempt to fix ..." 😆. Anyway; I will wait for the tests on b5def68f2b3c495da8d743f259df8103e418e3e3 to go green and then release a new version; let me know if this fixes it. The unit cache now reloads when it detects a change in version.

**Comment by jhhcs** [comment]
The [new release is out](https://github.com/binref/refinery/actions/runs/12029234188), please let me know if this fixed it!

**Comment by utkonos** [comment]
Still raising an exception:

```none
% pip list -o
Package         Version Latest Type
--------------- ------- ------ -----
binary-refinery 0.7.10  0.7.11 sdist
(venv) BinaryRefinery % pip list -o --format json | jq -r '.[].name' | xargs -n 1 pip install -U
Requirement already satisfied: binary-refinery in ./venv/lib/python3.13/site-packages (0.7.10)
Collecting binary-refinery
  Downloading binary_refinery-0.7.11.tar.gz (570 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 570.2/570.2 kB 5.6 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: colorama in ./venv/lib/python3.13/site-packages (from binary-refinery) (0.4.6)
Requirement already satisfied: defusedxml in ./venv/lib/python3.13/site-packages (from binary-refinery) (0.7.1)
Requirement already satisfied: macholib in ./venv/lib/python3.13/site-packages (from binary-refinery) (1.16.3)
Requirement already satisfied: msgpack>=1.0.0 in ./venv/lib/python3.13/site-packages (from binary-refinery) (1.1.0)
Requirement already satisfied: pefile in ./venv/lib/python3.13/site-packages (from binary-refinery) (2024.8.26)
Requirement already satisfied: pycryptodomex in ./venv/lib/python3.13/site-packages (from binary-refinery) (3.21.0)
Requirement already satisfied: pyelftools in ./venv/lib/python3.13/site-packages (from binary-refinery) (0.31)
Requirement already satisfied: setuptools in ./venv/lib/python3.13/site-packages (from binary-refinery) (75.6.0)
Requirement already satisfied: toml in ./venv/lib/python3.13/site-packages (from binary-refinery) (0.10.2)
Requirement already satisfied: wheel in ./venv/lib/python3.13/site-packages (from binary-refinery) (0.45.1)
Requirement already satisfied: python-magic in ./venv/lib/python3.13/site-packages (from binary-refinery) (0.4.27)
Requirement already satisfied: capstone in ./venv/lib/python3.13/site-packages (from binary-refinery) (5.0.3)
Requirement already satisfied: pyperclip in ./venv/lib/python3.13/site-packages (from binary-refinery) (1.9.0)
Requirement already satisfied: altgraph>=0.17 in ./venv/lib/python3.13/site-packages (from macholib->binary-refinery) (0.17.4)
Building wheels for collected packages: binary-refinery
  Building wheel for binary-refinery (pyproject.toml) ... done
  Created wheel for binary-refinery: filename=binary_refinery-0.7.11-py3-none-any.whl size=715285 sha256=80ee0bfba5bae6a75471d66297bc3b13189e6b908ad897a571e6c90f51eb70bf
  Stored in directory: /Users/username/Library/Caches/pip/wheels/e3/36/f4/ba7b53d63a820fe0a4dd2a6943193dee0eb5bf11b3fe976ae2
Successfully built binary-refinery
Installing collected packages: binary-refinery
  Attempting uninstall: binary-refinery
    Found existing installation: binary-refinery 0.7.10
    Uninstalling binary-refinery-0.7.10:
      Successfully uninstalled binary-refinery-0.7.10
Successfully installed binary-refinery-0.7.11
(venv) BinaryRefinery % binref foo
Traceback (most recent call last):
  File "/Users/username/Applications/BinaryRefinery/venv/bin/binref", line 8, in <module>
    sys.exit(explorer())
             ~~~~~~~~^^
  File "/Users/username/Applications/BinaryRefinery/venv/lib/python3.13/site-packages/refinery/explore.py", line 147, in explorer
    unit = getattr(refinery, name)
  File "/Users/username/Applications/BinaryRefinery/venv/lib/python3.13/site-packages/refinery/__init__.py", line 219, in __getattr__
    raise AttributeError(name)
AttributeError: httprequest
```

**Comment by huettenhain** [comment]
I think the root cause here is similar to what we saw in #65; I strongly suspect that importing `cgi` causes an import error on your system, and the unit cache is not robust against this.

**Comment by utkonos** [comment]
Yes, and the workaround works just fine. This is just a cosmetic issue. No worries!

**Comment by huettenhain** [comment]
Oh I fully intend to fix it; and I mean both problems:
- I already removed the dependency on the now deprecated cgi module in 00a03f3f74bd6396396c0c51aaa71eee5f9305c1.
- However, the unit cache should also be more robust against such issues; I will look into this next.

**Comment by utkonos** [comment]
Updated to .12 and no problems at all. Thanks @huettenhain
